---

name: automated-tests

on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches-ignore:
            - main

jobs:
    automated-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12
          - name: Install DSP-TOOLS
            run: pip3 install git+https://github.com/dasch-swiss/dsp-tools.git@wip/video-segment-audio-segment
          - name: start stack
            run: dsp-tools start-stack --no-prune
          - name: create data model
            run: dsp-tools create rosetta.json
          - name: upload data
            run: dsp-tools xmlupload rosetta.xml
